project_id = "izspjvegxdfgkgibpyst"

[functions.gerar-flashcards]
verify_jwt = false

[functions.gerar-estrutura-aula]
verify_jwt = false

[functions.buscar-proposicoes-recentes]
verify_jwt = false

[functions.buscar-plp-recentes]
verify_jwt = false

[functions.buscar-deputados]
verify_jwt = false

[functions.popular-proposicoes-manual]
verify_jwt = false

[functions.gerar-aula-artigo]
verify_jwt = false

[functions.gerar-plano-estudos]
verify_jwt = false

[functions.gerar-aula-livro]
verify_jwt = false

[functions.gerar-questoes-tema]
verify_jwt = false

[functions.gerar-questoes-lote]
verify_jwt = false

[functions.gerar-audio-questao]
verify_jwt = false

[functions.gerar-narracao]
verify_jwt = false

[functions.gerar-imagem-hf]
verify_jwt = false
